language: java

before_install:
  - pip install codecov

after_success:
  - codecov

services:
- redis-server

branches:
  only:
  - master

jdk:
- oraclejdk8

script:
- mvn -Djavax.xml.accessExternalSchema=all clean compile
- mvn package

install: /bin/true 
